# Generated by Django 5.0.1 on 2024-02-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Ник')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.IntegerField(verbose_name='Число проектов')),
            ],
        ),
    ]
