# Generated by Django 5.0.1 on 2024-02-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Ник')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='img/team_img')),
                ('count', models.IntegerField(verbose_name='Число проектов')),
            ],
        ),
        migrations.DeleteModel(
            name='Database',
        ),
    ]
