# Generated by Django 5.0.1 on 2024-02-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatabase', '0002_teamdatabase_delete_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdatabase',
            name='href',
            field=models.TextField(default='https://web.telegram.org/a/', max_length=100, verbose_name='Ссылка'),
        ),
    ]
