# Generated by Django 5.0.1 on 2024-02-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatabase', '0003_teamdatabase_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamdatabase',
            old_name='description',
            new_name='desc',
        ),
    ]
