# Generated by Django 5.0.1 on 2024-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatabase', '0004_rename_description_teamdatabase_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdatabase',
            name='href',
            field=models.URLField(default='https://web.telegram.org/a/', max_length=100, verbose_name='Ссылка'),
        ),
    ]
