# Generated by Django 5.0.1 on 2024-02-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatabase', '0006_alter_teamdatabase_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdatabase',
            name='img',
            field=models.ImageField(height_field='350', upload_to='images/', width_field='350'),
        ),
    ]
