# Generated by Django 5.0.1 on 2024-02-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatabase', '0008_teamdatabase_img_height_teamdatabase_img_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdatabase',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='teamdatabase',
            name='img_width',
        ),
    ]
