# Generated by Django 5.0.1 on 2024-02-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatabase', '0009_remove_teamdatabase_img_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.TextField(max_length=1000, verbose_name='Описание')),
                ('img', models.ImageField(height_field='img_height', upload_to='images/', width_field='img_width')),
                ('href', models.URLField(default='https://web.telegram.org/a/', max_length=100, verbose_name='Ссылка')),
            ],
        ),
    ]
